/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeartbeatRouteImport } from './routes/heartbeat'
import { Route as OnlineOfflineRouteImport } from './routes/online-offline'
import { Route as ReconnectionRouteImport } from './routes/reconnection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeartbeatRoute = HeartbeatRouteImport.update({
  id: '/heartbeat',
  path: '/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineOfflineRoute = OnlineOfflineRouteImport.update({
  id: '/online-offline',
  path: '/online-offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconnectionRoute = ReconnectionRouteImport.update({
  id: '/reconnection',
  path: '/reconnection',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heartbeat': typeof HeartbeatRoute
  '/online-offline': typeof OnlineOfflineRoute
  '/reconnection': typeof ReconnectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heartbeat': typeof HeartbeatRoute
  '/online-offline': typeof OnlineOfflineRoute
  '/reconnection': typeof ReconnectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heartbeat': typeof HeartbeatRoute
  '/online-offline': typeof OnlineOfflineRoute
  '/reconnection': typeof ReconnectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/heartbeat' | '/online-offline' | '/reconnection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/heartbeat' | '/online-offline' | '/reconnection'
  id: '__root__' | '/' | '/heartbeat' | '/online-offline' | '/reconnection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeartbeatRoute: typeof HeartbeatRoute
  OnlineOfflineRoute: typeof OnlineOfflineRoute
  ReconnectionRoute: typeof ReconnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heartbeat': {
      id: '/heartbeat'
      path: '/heartbeat'
      fullPath: '/heartbeat'
      preLoaderRoute: typeof HeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-offline': {
      id: '/online-offline'
      path: '/online-offline'
      fullPath: '/online-offline'
      preLoaderRoute: typeof OnlineOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconnection': {
      id: '/reconnection'
      path: '/reconnection'
      fullPath: '/reconnection'
      preLoaderRoute: typeof ReconnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeartbeatRoute: HeartbeatRoute,
  OnlineOfflineRoute: OnlineOfflineRoute,
  ReconnectionRoute: ReconnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
